spring.datasource.url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none

spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.format_sql: true

spring.liquibase.change-log: classpath:db/db.changelog-master.xml
